kotlin.code.style=official
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
#org.gradle.unsafe.isolated-projects=true
kotlin.native.ignoreDisabledTargets=true
group=org.jetbrains.kotlin.compiler.plugin.template
version=0.1.0-SNAPSHOT
org.jetbrains.kotlin.compiler.plugin.devkit.testAgainst=2.4.20-dev-7885, 2.5.0-dev-498
org.jetbrains.kotlin.compiler.plugin.devkit.companionLibraries=:plugin-annotations
org.jetbrains.kotlin.compiler.plugin.devkit.compilerPlugin=:compiler-plugin